import { Router } from "express";
import { healthRouter } from "./health.router";
import { authRouter } from "../auth/routes/auth.router";
import { createAIRouter } from "../ai/routes/ai.router";
import { crmRouter } from "../crm/routes/crm.router";
import { projectsRouter } from "../projects/routes/projects.router";
import { milestonesRouter } from "../projects/routes/milestones.router";
import { tasksRouter } from "../tasks/routes/tasks.router";
import { dashboardRouter } from "../dashboard/routes/dashboard.router";
import { searchRouter } from "../search/routes/search.router";

export const v1Router = Router();
v1Router.use("/health", healthRouter);
v1Router.use("/auth", authRouter);
v1Router.use("/ai", createAIRouter());
v1Router.use("/crm", crmRouter);
v1Router.use("/projects", projectsRouter);
v1Router.use("/milestones", milestonesRouter);
v1Router.use("/tasks", tasksRouter);
v1Router.use("/dashboard", dashboardRouter);
v1Router.use("/search", searchRouter);
