import React, { useEffect, useState } from "react";
import { Search, X } from "lucide-react";
import { apiClient } from "../../api/client";
import type { GlobalSearchResponse } from "@omnidesk/shared-types";

export const GlobalSearchModal: React.FC<{ open: boolean; onClose: () => void; onNavigate: (tab: "dashboard"|"ai"|"projects"|"tasks"|"crm") => void }> = ({ open, onClose, onNavigate }) => {
 const [query,setQuery]=useState(""); const [data,setData]=useState<GlobalSearchResponse|null>(null);
 useEffect(()=>{ if(!open){setQuery("");setData(null);return;} const key=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose();};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key);},[open,onClose]);
 useEffect(()=>{ if(!open||query.trim().length<1)return; const timer=window.setTimeout(async()=>{const token=apiClient.getAccessToken();const res=await fetch(`/api/v1/search?q=${encodeURIComponent(query)}&limit=30`,{headers:{Authorization:`Bearer ${token||""}`}});if(res.ok){const body=await res.json();setData(body.data);}},250);return()=>window.clearTimeout(timer);},[query,open]);
 if(!open)return null;
 return <div style={{position:"fixed",inset:0,zIndex:1000,background:"rgba(0,0,0,.65)",display:"flex",justifyContent:"center",paddingTop:"10vh"}} onMouseDown={onClose}><div className="glass-card" style={{width:"min(720px,92vw)",maxHeight:"70vh",overflow:"hidden"}} onMouseDown={e=>e.stopPropagation()}><div style={{display:"flex",alignItems:"center",gap:10,padding:14,borderBottom:"1px solid var(--border-subtle)"}}><Search size={20}/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search projects, tasks, CRM, milestones, AI..." style={{flex:1,background:"transparent",border:0,outline:0,color:"var(--text-primary)",fontSize:16}}/><button onClick={onClose}><X size={18}/></button></div><div style={{overflowY:"auto",padding:10}}>{data&&data.total===0&&<div style={{padding:24,color:"var(--text-muted)",textAlign:"center"}}>No results found</div>}{data&&Object.entries(data.results).map(([category,items])=>items.length?<div key={category} style={{marginBottom:12}}><div style={{fontSize:11,textTransform:"uppercase",color:"var(--brand-cyan)",fontWeight:700,padding:"6px 8px"}}>{category}</div>{items.map(item=><button key={item.id} onClick={()=>{onNavigate(item.navigation.tab);onClose();}} style={{display:"block",width:"100%",textAlign:"left",padding:10,border:0,background:"transparent",color:"var(--text-primary)",cursor:"pointer",borderRadius:8}}><div style={{fontWeight:600}}>{item.title}</div><div style={{fontSize:12,color:"var(--text-muted)"}}>{item.subtitle||item.status||""}</div></button>)}</div>:null)}</div></div></div>;
};
